Treewide: Fix gcc warns
hw_breakpoint: fix warning

../arch/arm64/kernel/hw_breakpoint.c:364:5: note: parameter passing for argument of type 'struct arch_hw_breakpoint_ctrl' changed in GCC 9.1
  364 | int arch_bp_generic_fields(struct arch_hw_breakpoint_ctrl ctrl,
      |     ^~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

zram_drv: Fix warning -Wformat Wrong issue after zram override patch

In file included from ../include/linux/printk.h:6,
                 from ../include/linux/kernel.h:13,
                 from ../include/linux/list.h:8,
                 from ../include/linux/module.h:9,
                 from ../drivers/block/zram/zram_drv.c:18:
../drivers/block/zram/zram_drv.c: In function 'disksize_store':
../include/linux/kern_levels.h:4:18: error: format '%li' expects argument of type 'long int', but argument 2 has type 'u64' {aka 'long long unsigned int'} [-Werror=format=]
    4 | #define KERN_SOH '\001'  /* ASCII Start Of Header */
      |                  ^~~~~~
../include/linux/kern_levels.h:13:19: note: in expansion of macro 'KERN_SOH'
   13 | #define KERN_INFO KERN_SOH '6' /* informational */
      |                   ^~~~~~~~
../include/linux/printk.h:259:9: note: in expansion of macro 'KERN_INFO'
  259 |  printk(KERN_INFO pr_fmt(fmt), ##__VA_ARGS__)
      |         ^~~~~~~~~
../drivers/block/zram/zram_drv.c:1502:2: note: in expansion of macro 'pr_info'
 1502 |  pr_info('Overriding zram size to %li', disksize);
      |  ^~~~~~~
  CC      fs/f2fs/recovery.o

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

ASoC: msm: qdsp6v2: Remove duplicate const specifier

Fixes the following GCC 7.3.0 warnings: duplicate ‘const’
declaration specifier [-Wduplicate-decl-specifier]

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

Revert "sound/soc/msm/qdsp6v2/msm-pcm-routing-v2.c: remove a nested loop"

Gcc complains:
  CC      lib/strncpy_from_user.o
../sound/soc/msm/qdsp6v2/msm-pcm-routing-v2.c: In function 'msm_pcm_routing_set_channel_mixer_cfg':
../sound/soc/msm/qdsp6v2/msm-pcm-routing-v2.c:888:41: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
  888 |  for (i = 0, j = 0; i < ADM_MAX_CHANNELS, j < ADM_MAX_CHANNELS; i++, j++)
      |                                         ^
  AR      net/ipc_router/built-in.o
  CC      sound/soc/msm/msm-dai-fe.o
  CC      net/core/secure_seq.o
  CC      lib/strnlen_user.o

This reverts commit e70b9194cb2083f19edde64535012958b62ea2a6.

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

ASoC: msm: qdsp6v2: Fix bool comparision warning

Fixes the following GCC 7.3.0 warning: comparison of constant ‘0’ with
boolean expression is always false [-Wbool-compare]

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

drivers: i2c: Fix Wduplicate decl specifier warning

../drivers/i2c/busses/i2c-msm-v2.c:2874:19: warning: duplicate ‘const’ declaration specifier [-Wduplicate-decl-specifier]
 static const char const *i2c_msm_adapter_name = "MSM-I2C-v2-adapter";
                   ^~~~~

Signed-off-by: Fiqri Ardyansyah <fiqri15072019@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

fpc1020_tee: Remove duplicate const specifier

Gcc warn:
  AR      drivers/i2c/built-in.o
  CC      net/ipv4/xfrm4_output.o
  CC      drivers/irqchip/irq-gic-common.o
../drivers/input/fingerprint/fpc/fpc1020_platform_tee.c:81:33: error: duplicate 'const' declaration specifier [-Werror=duplicate-decl-specifier]
   81 | static const struct vreg_config const vreg_conf[] = {
      |                                 ^~~~~
  CC      drivers/iio/inkern.o
  AR      net/netfilter/netfilter.o
  CC      drivers/irqchip/irq-gic-v2m.o

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

media/msm: vidc: Avoid implicit middle operand

../drivers/media/platform/msm/vidc/msm_vidc_common.c: In function ‘msm_comm_qbuf’:
../drivers/media/platform/msm/vidc/msm_vidc_common.c:3858:17: warning: the omitted middle operand in ‘?:’ will always be ‘true’, suggest explicit middle operand [-Wparentheses]
 3858 |  defer = defer ?: inst->state != MSM_VIDC_START_DONE;
      |                 ^
../drivers/media/platform/msm/vidc/msm_vidc_common.c:3865:17: warning: the omitted middle operand in ‘?:’ will always be ‘true’, suggest explicit middle operand [-Wparentheses]
 3865 |  defer = defer ?: vbuf && vbuf->flags & V4L2_MSM_BUF_FLAG_DEFER;
      |                 ^
../drivers/media/platform/msm/vidc/msm_vidc_common.c:3868:17: warning: the omitted middle operand in ‘?:’ will always be ‘true’, suggest explicit middle operand [-Wparentheses]
 3868 |  defer = defer ?: batch_mode && (|| !capture_count);
      |                 ^

Signed-off-by: Albert I <kras@raphielgang.org>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

power/smb-lib: Remove duplicate const declaration in smblib_apsd_results

  CC      drivers/platform/msm/ipa/ipa_v3/ipa_rt.o
../drivers/power/supply/qcom/smb-lib.c:234:33: error: duplicate 'const' declaration specifier [-Werror=duplicate-decl-specifier]
  234 | static const struct apsd_result const smblib_apsd_results[] = {
      |                                 ^~~~~
  CC      drivers/scsi/scsi_pm.o
  CC      drivers/platform/msm/ipa/ipa_v2/ipa_rt.o

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

ipa_v2: Fix memset-elt-size warning

  CC      drivers/regulator/cpr3-util.o
../drivers/platform/msm/ipa/ipa_v2/ipa_rt.c: In function '__ipa_generate_rt_hw_rule_v2':
../drivers/platform/msm/ipa/ipa_v2/ipa_rt.c:57:3: error: 'memset' used with length equal to number of elements without multiplication by element size [-Werror=memset-elt-size]
   57 |   memset(tmp, 0, (IPA_RT_FLT_HW_RULE_BUF_SIZE/4));
      |   ^~~~~~
  CC      drivers/slimbus/slimbus.o
  CC      drivers/scsi/sd.o
  CC      drivers/platform/msm/ipa/ipa_v3/ipa_dp.o
  AR      drivers/pci/host/built-in.o

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

msm: mdss: Remove duplicate const specifier

Fixes the following GCC 7.3.0 warnings: duplicate ‘const’ declaration
specifier [-Wduplicate-decl-specifier]

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

fbdev: Fix bool-operation warning

  CC      drivers/usb/phy/class-dual-role.o
../drivers/video/fbdev/msm/mdss_mdp_intf_video.c: In function 'mdss_mdp_video_wait4comp':
../drivers/video/fbdev/msm/mdss_mdp_intf_video.c:1239:19: error: increment of a boolean expression [-Werror=bool-operation]
 1239 |    ctx->polling_en++;
      |                   ^~
  CC      drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_request_manager.o
  AR      drivers/usb/pd/built-in.o
  CC      drivers/usb/phy/phy-generic.o
  CC      drivers/soc/qcom/scm-boot.o
  CC      drivers/usb/storage/scsiglue.o
  CC      drivers/soc/qcom/watchdog_v2.o

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>

qcacld-3.0: fix gcc 9.1 warns

  CC      drivers/staging/qcacld-3.0/core/mac/src/pe/lim/lim_process_assoc_rsp_frame.o
  CC      drivers/staging/qcacld-3.0/core/mac/src/pe/lim/lim_process_auth_frame.o
  CC      drivers/staging/qcacld-3.0/core/mac/src/pe/lim/lim_process_beacon_frame.o
../drivers/staging/qcacld-3.0/core/mac/src/pe/lim/lim_assoc_utils.c: In function 'lim_populate_vht_caps':
../drivers/staging/qcacld-3.0/core/mac/src/pe/lim/lim_assoc_utils.c:2035:17: note: parameter passing for argument of type 'tDot11fIEVHTCaps' {aka 'struct sDot11fIEVHTCaps'} changed in GCC 9.1
 2035 | static uint32_t lim_populate_vht_caps(tDot11fIEVHTCaps input_caps)
      |                 ^~~~~~~~~~~~~~~~~~~~~
  CC      drivers/staging/qcacld-3.0/core/mac/src/pe/lim/lim_process_cfg_updates.o
  CC      drivers/staging/qcacld-3.0/core/mac/src/pe/lim/lim_process_deauth_frame.o
  CC      drivers/staging/qcacld-3.0/core/mac/src/pe/lim/lim_process_disassoc_frame.o
  CC      drivers/staging/qcacld-3.0/core/mac/src/pe/lim/lim_process_message_queue.o

  CC      drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/linux/src/qdf_mem.o
  CC      drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/linux/src/qdf_nbuf.o
  CC      drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/linux/src/qdf_threads.o
../drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c: In function 'sir_copy_caps_info':
../drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:2455:6: note: parameter passing for argument of type 'tDot11fFfCapabilities' {aka 'struct sDot11fFfCapabilities'} changed in GCC 9.1
 2455 | void sir_copy_caps_info(tpAniSirGlobal mac_ctx, tDot11fFfCapabilities caps,
      |      ^~~~~~~~~~~~~~~~~~
  CC      drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/linux/src/qdf_crypto.o
  CC      drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/linux/src/qdf_trace.o
  CC      drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/linux/src/qdf_idr.o
  CC      drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/src/qdf_cpuhp.o

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>